# -*- coding: utf-8 -*-
"""reviewType_Chart1_tuning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NBcxovD6OPzW0PpO_qDggakWgunWEtCm
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import reviewtype_utility_functions as rcuf
# %matplotlib inline
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import altair as alt
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'
import numpy as np
import random
import re
from collections import Counter, defaultdict
from nltk.tokenize import word_tokenize
from sklearn.metrics import f1_score
import nltk
import warnings
warnings.filterwarnings('ignore')

from altair_saver import save



if __name__ == '__main__':
    import argparse
    path_visualization='report/'
    parser = argparse.ArgumentParser()
    parser.add_argument('input_file', help='review label dataset processed (csv)')
    args = parser.parse_args()
    eval_df = pd.read_csv(args.input_file)
    model_compare_df = rcuf.build_df__phobert_comparision(eval_df)
    model_compare_chart=rcuf.combined_graph(model_compare_df)
    save(model_compare_chart, path_visualization+'reviewType_model_compare.png')
    print('Model comparison chart is saved ,please check')

