# -*- coding: utf-8 -*-
"""reviewType_Chart2_compare_traditional.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iZhr2y_qDFYokg4_DqljArMhL5Mri1W2
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import reviewtype_utility_functions as rcuf
# %matplotlib inline
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import altair as alt
import pandas as pd
pd.options.mode.chained_assignment = None  
import numpy as np
import random
import re
from collections import Counter, defaultdict
from nltk.tokenize import word_tokenize
from sklearn.metrics import f1_score
import nltk
import warnings
warnings.filterwarnings('ignore')
from altair_saver import save



if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    model_compare_chart = rcuf.compare_tranditional()   
    save(model_compare_chart, '/content/drive/MyDrive/git_pipeline_capstone/reviewType_model_compare_traditional.png')
    print('The comparison chart is now ready..please check.')

