# -*- coding: utf-8 -*-
"""reviewType_Validate_phobert_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19i8YLMvV2uVauOjER93GvJpb7Omc1bpY
"""

import reviewtype_utility_functions as rcuf
import pandas as pd
pd.options.mode.chained_assignment = None
import numpy as np
import random
import torch
from transformers import BertTokenizer, logging
from transformers import AutoModel, AutoTokenizer
import altair as alt
alt.renderers.enable('default')
import warnings
warnings.filterwarnings('ignore')
no_deprecation_warning=True
logging.set_verbosity_error()

MAX_LEN = 256
RANDOM_SEED = 42
random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)
torch.manual_seed(RANDOM_SEED)
torch.cuda.manual_seed_all(RANDOM_SEED)

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

hidden_dropout_prob = 0.4
attention_probs_dropout_prob = 0.1
pre_trained_model = 'vinai/phobert-base'
model_type = pre_trained_model.split('/')[0]
batch_size = 8
epochs = 20
Ir = 1e-5
eps = 1e-8
train_data_provider = 'Suwasit'

if __name__ == '__main__':

    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument('input_file', help='sentiment analysis reviews label data with train and validation split(csv)')
    args = parser.parse_args()
    reviews_label_df = pd.read_csv(args.input_file)
    df_test=reviews_label_df[reviews_label_df.data_category=='test']
    tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base")
    dataloader_test = rcuf.create_data_loader(df_test, tokenizer, MAX_LEN, batch_size)
    model = rcuf.build_Bert_model(pre_trained_model, attention_probs_dropout_prob, hidden_dropout_prob)
    model_path =  '/content/drive/MyDrive/git_pipeline_capstone/reviewtype_phobert_model.pt'
    model = torch.load(model_path)
    _, predictions, true_vals = rcuf.evaluate(model,dataloader_test)
    accuracy_per_class_df = rcuf.accuracy_per_class(predictions, true_vals, model_type, epochs, train_data_provider)
    accuracy_per_class_df_path = '/content/drive/MyDrive/git_pipeline_capstone/reviewtype__accuracy_per_class_df.csv'
    accuracy_per_class_df.to_csv(accuracy_per_class_df_path, index=False)
    eval_df = pd.read_csv('/content/drive/MyDrive/git_pipeline_capstone/reviewtype_pho_bert_eval_df.csv')
    true_vals= true_vals.reshape(-1)
    confusion_chart=rcuf.confusion_matrix_function (true_vals,predictions)
    print(confusion_chart)
    best_epoch_F1_score_macro = eval_df[eval_df['F1_score_macro'] == max(eval_df['F1_score_macro'])]['epoch'].values[0]