# -*- coding: utf-8 -*-
"""reviewType__prepare_review_label

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15VKkpeBMG6EM1SFq61zvxl208VHWMtw3
"""

import reviewtype_utility_functions as rcuf



if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser()

    parser.add_argument('input_file', help='review label dataset (excel)')
    parser.add_argument('output_file', help='processed review label dataset (csv)')

    args = parser.parse_args()

    import_data = rcuf.import_review_data(args.input_file, 'Database_LZD')
    output_data = rcuf.oversample_minority_class(import_data)
    output_data.to_csv(args.output_file, index=False)