# -*- coding: utf-8 -*-
"""reviewType__train_test_val_split.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_z-ih0e2dOlMcdzX9kgxcXOp6OJh7D1Y
"""

import pandas as pd
import reviewtype_utility_functions as rcuf


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('input_file', help='review label dataset processed (csv)')
    parser.add_argument('output_file', help='review label dataset with data category (csv)')
    args = parser.parse_args()

    data_category_df = rcuf.set_data_category_in_df(pd.read_csv(args.input_file))
    data_category_df.to_csv(args.output_file, index=False)
    print(data_category_df.data_category.value_counts())